name: autofix.ci # needed to securely identify the workflow

on:
  pull_request:

jobs:
  fix:
    name: Fix
    runs-on: ubuntu-latest
    env:
      YARN_ENABLE_IMMUTABLE_INSTALLS: false
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          cache: "yarn"

      - name: Install Dependencies
        run: yarn

      - uses: autofix-ci/action@v1
        with:
          commit-message: "Apply automated changes"
