name: autofix.ci # needed to securely identify the workflow

on:
  pull_request:

jobs:
  debug:
    runs-on: ubuntu-latest
    steps:
      - run: echo run

  fix:
    uses: fisker/shared-workflows/.github/workflows/autofix.yml@main
