# Test Test reusable workflow - automated-fix https://github.com/fisker/shared-workflows/blob/main/.github/workflows/automated-fix.yml
name: autofix.ci # needed to securely identify the workflow

on:
  pull_request:
  push:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  fix:
    if: github.repository == 'fisker/playground'
    name: Run automated fix
    uses: fisker/shared-workflows/.github/workflows/automated-fix.yml@main
