# https://github.com/fisker/shared-workflows/blob/main/.github/workflows/reusable-workflows/scheduled-task.yml
name: Test reusable workflow - scheduled-task

on:
  workflow_dispatch:
  schedule:
    # “At 00:00 on day-of-month 1 and on Sunday in January.” https://crontab.guru/#0_0_1_1_0
    - cron: "0 0 1 1 0"

jobs:
  update:
    if: github.event_name != 'schedule' || github.repository == 'fisker/update'
    name: Run update
    uses: fisker/shared-workflows/.github/workflows/reusable-workflows/scheduled-task.yml@main
